### ISSUE TITLE
Support custom developer fields

### ISSUE THREAD

**Issue by richardbrodie** [richardbrodie/fit-rs#3]

**Comment by Libbum** [comment]
Hi Richard, I see you're actively working on a big re-write, so thought I'd check with you before doing anything about this issue. I've got a Wahoo Elemnt BOLT that I'd like to get functioning with your crate&mdash;it has developer fields apparently.

Is your current re-write working on including these, or could this be worked on independently? Could you let me know what you've done (if anything) already?

**Comment by richardbrodie** [comment]
Hey, thanks for getting in touch. Currently the rewrite is only aimed at the same level of functionality as the released version (for simplicity's sake). But supporting developer fields is absolutely next on the list. 

I should hopefully be more or less ready with the rewrite in a few days. There's more speed that could be gained, but I feel like that can be just as easily accomplished at a later date or else I might never be finished. A ~10x speedup is good enough for now :)

The good news is that I have an old elixir implementation that supports developer fields so it should go pretty quickly using that logic as a template.

**Comment by Libbum** [comment]
Cool, OK. Well it'd probably be worth me waiting to assist once that's done then so I can get acquainted with the new codebase. Ping me when you're ready and I'll help out!

**Comment by richardbrodie** [comment]
Right, the new rewrite is more or less ready now, and merged to the master branch. It's not finished, but the design is stable enough.

I'll make a start on this issue now.

**Comment by Libbum** [comment]
Great! Since you have your elixir code I guess there's no need for me to delve into the API at all. If you run into issues, let me know. I can run some tests with my fit files on the initial implementation once you've translated the elixir template.

**Comment by richardbrodie** [comment]
Closed in 8b4af8a34601b51f60de220030170539442c593b
